#!/bin/sh
# Script to install preload.conf

PREFIX=${PKG_PREFIX-/usr/local}

if [ "$2" != "POST-INSTALL" ] ; then
   exit 0
fi

# If this is during staging, we can skip for now
echo $PREFIX | grep -q '/stage/'
if [ $? -eq 0 ] ; then
   exit 0
fi

# REMOVEME - Temp fix to ensure i915kms is loaded on upgraded systems
# 8-29-2016
if [ -e "/etc/rc.conf.trueos" ] ; then
  set +e
  grep -q "i915kms" /etc/rc.conf.trueos
  if [ $? -eq 0 ] ; then
    sysrc -f /etc/rc.conf kldload_i915kms="i915kms"
  fi
  set -e
fi

## REMOVEME - Eventually nuke, but for now determine if we need to copy modesetting
# driver over to xorg.conf
# 9-16-2016
if [ -e "/var/log/Xorg.0.log" ] ; then
  set +e
  grep -q "modesetting" /var/log/Xorg.0.log
  if [ $? -eq 0 ] ; then
    cp ${PREFIX}/share/trueos/cardDetect/XF86Config.modesetting /etc/X11/xorg.conf
  fi
  set -e
fi

# Copy over customizations for TrueOS
  install -m 644 ${PREFIX}/share/trueos/conf/loader.conf.trueos /boot/loader.conf.trueos
  install -m 644 ${PREFIX}/share/trueos/conf/brand-trueos.4th /boot/brand-trueos.4th
  install -m 644 ${PREFIX}/share/trueos/desktop-defaults/etc/conf.d/modules /etc/conf.d/modules

if [ ! -e "${PREFIX}/etc/trueos.conf" ] ; then
  # Do the first-time setup
  echo "Doing first-time bootstrap"
  tar cvf - -C ${PREFIX}/share/trueos/desktop-defaults/ . 2>/dev/null | tar xvpf - -C / 2>/dev/null
fi

# Enable the OpenRC services
set +e
/sbin/rc-update add ipfw boot
/sbin/rc-update add devd boot
/sbin/rc-update add bridge boot
/sbin/rc-update add network boot
/sbin/rc-update add automount default
/sbin/rc-update add statd default
/sbin/rc-update add lockd default
/sbin/rc-update add rpcbind default
/sbin/rc-update add dhcpcd default
/sbin/rc-update add cupsd default
/sbin/rc-update add wpa_supplicant default
/sbin/rc-update add openntpd default
/sbin/rc-update add pcdm default
/sbin/rc-update add sysadm default
/sbin/rc-update add dbus default
/sbin/rc-update add trueosinit default
/sbin/rc-update add moused default

# Enable OpenRC settings
set +e
sysrc -f /etc/rc.conf rc_parallel="YES"
sysrc -f /etc/rc.conf rc_logger="YES"
sysrc -f /etc/rc.conf rc_log_path="/var/log/rc.log"

exit 0
