#!/bin/sh
# Script to install preload.conf

PREFIX=${PKG_PREFIX-/usr/local}

if [ "$2" != "POST-INSTALL" ] ; then
   exit 0
fi

# If this is during staging, we can skip for now
echo $PREFIX | grep -q '/stage/'
if [ $? -eq 0 ] ; then
   exit 0
fi

# REMOVEME - Temp fix to ensure i915kms is loaded on upgraded systems
# 8-29-2016
if [ -e "/etc/rc.conf.trueos" ] ; then
  set +e
  grep -q "i915kms" /etc/rc.conf.trueos
  if [ $? -eq 0 ] ; then
    sysrc -f /etc/rc.conf kldload_i915kms="i915kms"
  fi
  set -e
fi

## REMOVEME - Eventually nuke, but for now determine if we need to copy modesetting
# driver over to xorg.conf
# 9-16-2016
if [ -e "/var/log/Xorg.0.log" ] ; then
  set +e
  grep -q "modesetting" /var/log/Xorg.0.log
  if [ $? -eq 0 ] ; then
    cp ${PREFIX}/share/trueos/cardDetect/XF86Config.modesetting /etc/X11/xorg.conf
  fi
  set -e
fi

# Copy over customizations for TrueOS
  install -m 644 ${PREFIX}/share/trueos/conf/loader.conf.trueos /boot/loader.conf.trueos
  install -m 644 ${PREFIX}/share/trueos/conf/brand-trueos.4th /boot/brand-trueos.4th
  install -m 644 ${PREFIX}/share/trueos/desktop-defaults/etc/conf.d/modules /etc/conf.d/modules

if [ ! -e "${PREFIX}/etc/trueos.conf" ] ; then
  # Do the first-time setup
  echo "Doing first-time bootstrap"
  if [ -e "/etc/defaults/trueos-desktop" ] ; then
    tar cvf - -C ${PREFIX}/share/trueos/desktop-defaults/ . 2>/dev/null | tar xvpf - -C / 2>/dev/null
  else
    tar cvf - -C ${PREFIX}/share/trueos/server-defaults/ . 2>/dev/null | tar xvpf - -C / 2>/dev/null
  fi
fi

# Enable the OpenRC services
set +e
if [ -e "/etc/defaults/trueos-desktop" ] ; then
    /sbin/rc-update add ipfw boot
    /sbin/rc-update add dhcpcd default
    /sbin/rc-update add wpa_supplicant default
    /sbin/rc-update add openntpd default
    /sbin/rc-update add pcdm default
else
    /sbin/rc-update add ipfw boot
    /sbin/rc-update add dhcpcd default
    /sbin/rc-update add wpa_supplicant default
fi

exit 0
