#!/bin/sh
# Script to install preload.conf

PREFIX=${PKG_PREFIX-/usr/local}

if [ "$2" != "POST-INSTALL" ] ; then
   exit 0
fi

set +e

# If this is during staging, we can skip for now
echo $PREFIX | grep -q '/stage/'
if [ $? -eq 0 ] ; then
   exit 0
fi

# REMOVEME - Temp fix to ensure i915kms is loaded on upgraded systems
# 8-29-2016
if [ -e "/etc/rc.conf.trueos" ] ; then
  grep -q "i915kms" /etc/rc.conf.trueos
  if [ $? -eq 0 ] ; then
    sysrc -f /etc/rc.conf kldload_i915kms="i915kms"
  fi
fi

## REMOVEME - Eventually nuke, but for now determine if we need to copy modesetting
# driver over to xorg.conf
# 9-16-2016
if [ -e "/var/log/Xorg.0.log" ] ; then
  grep -q "modesetting" /var/log/Xorg.0.log
  if [ $? -eq 0 ] ; then
    cp ${PREFIX}/share/trueos/cardDetect/XF86Config.modesetting /etc/X11/xorg.conf
  fi
fi

# Copy over customizations for TrueOS
  install -m 644 ${PREFIX}/share/trueos/conf/brand-trueos.4th /boot/brand-trueos.4th

if [ ! -e "${PREFIX}/etc/trueos.conf" ] ; then
  # Do the first-time setup
  echo "Doing first-time bootstrap"
  tar cvf - -C ${PREFIX}/share/trueos/desktop-defaults/ . 2>/dev/null | tar xvpf - -C / 2>/dev/null
fi

# Copy over some defaults on upgrade
cp ${PREFIX}/share/trueos/desktop-defaults/etc/devfs.rules /etc/devfs.rules

# Enable the OpenRC services

if [ ! -e "/var/.openrc-migrate-1" ] ; then
  /sbin/rc-update add ipfw boot
  /sbin/rc-update add devd boot
  /sbin/rc-update add devfs boot
  /sbin/rc-update add routing boot
  /sbin/rc-update add automount default
  /sbin/rc-update add statd default
  /sbin/rc-update add lockd default
  /sbin/rc-update add rpcbind default
  /sbin/rc-update add cupsd default
  /sbin/rc-update add cups_browsed default
  /sbin/rc-update delete dhcpcd default
  /sbin/rc-update delete wpa_supplicant default
  /sbin/rc-update add openntpd default
  /sbin/rc-update add pcdm default
  /sbin/rc-update add sysadm default
  /sbin/rc-update add dbus default
  /sbin/rc-update add hald default
  /sbin/rc-update add trueosinit default
  /sbin/rc-update add moused default
fi
touch /var/.openrc-migrate-1

if [ ! -e "/var/.openrc-migrate-2" ] ; then
  /sbin/rc-update add bsdstats default
  /sbin/rc-update add automountd default
  /sbin/rc-update add autounmountd default
fi
touch /var/.openrc-migrate-2

exit 0
